const dotenv = require('dotenv').config();
const connectDB = require('./connect/database');
const Book = require('./models/taskModel');

const cover = (seed) => `https://picsum.photos/seed/${seed}/800/1100`;

const books = [
    {
        title: 'Kronike ne gur',
        author: 'Ismail Kadare',
        category: 'Roman shqiptar',
        pages: 320,
        description: 'Nje roman mbi femijerine, qytetin dhe kujtesen ne nje kohe lufte.',
        isbn: '978-99927-1-625-0',
        publisher: 'Onufri',
        publishedYear: 1971,
        language: 'Shqip',
        edition: 'Botim modern',
        shelfLocation: 'A-01',
        availability: 'available',
        copies: 4,
        coverUrl: cover('kronike-ne-gur'),
        longDescription: 'Romani ndjek atmosferen e nje qyteti te gurte dhe menyren si ngjarjet historike kalojne neper syrin e nje femije. Libri nderthur kujtimin personal me tensionin e kohes dhe krijon nje tablo te dendur te jetes qytetare.',
    },
    {
        title: 'Prilli i thyer',
        author: 'Ismail Kadare',
        category: 'Roman shqiptar',
        pages: 216,
        description: 'Nje histori mbi kanunin, fatin dhe ciklin e gjakmarrjes.',
        isbn: '978-99927-1-307-5',
        publisher: 'Onufri',
        publishedYear: 1978,
        language: 'Shqip',
        edition: 'Ribotim',
        shelfLocation: 'A-02',
        availability: 'borrowed',
        copies: 2,
        coverUrl: cover('prilli-i-thyer'),
        longDescription: 'Libri trajton perplasjen midis tradites dhe jetes individuale. Ngjarja ndertohet rreth nje bote ku ligji zakonor percakton fatet e njerezve dhe ku liria personale mbetet e kufizuar nga detyrime te trasheguara.',
    },
    {
        title: 'Dimri i vetmise se madhe',
        author: 'Ismail Kadare',
        category: 'Roman shqiptar',
        pages: 448,
        description: 'Roman politik dhe shoqeror mbi izolimin dhe atmosferen e nje epoke.',
        isbn: '978-99927-1-805-9',
        publisher: 'Onufri',
        publishedYear: 1973,
        language: 'Shqip',
        edition: 'Ribotim',
        shelfLocation: 'A-03',
        availability: 'available',
        copies: 3,
        coverUrl: cover('dimri-vetmise-madhe'),
        longDescription: 'Ky roman vendos personazhet ne nje periudhe historike te tensionuar dhe eksploron ndikimin e politikes mbi jeten private. Ai bashkon rrefimin social, dialogun politik dhe vezhgimin psikologjik.',
    },
    {
        title: 'Gjenerali i ushtrise se vdekur',
        author: 'Ismail Kadare',
        category: 'Roman shqiptar',
        pages: 248,
        description: 'Nje gjeneral kthehet ne Shqiperi per te mbledhur eshtrat e ushtareve.',
        isbn: '978-99927-1-201-6',
        publisher: 'Onufri',
        publishedYear: 1963,
        language: 'Shqip',
        edition: 'Botim klasik',
        shelfLocation: 'A-04',
        availability: 'available',
        copies: 5,
        coverUrl: cover('gjenerali-ushtrise-vdekur'),
        longDescription: 'Romani trajton kujtesen e luftes, fajin dhe absurditetin e misioneve qe vijne shume vone. Udhetimi i gjeneralit shnderrohet ne perballje me nje vend, me historine dhe me hijet e se shkuares.',
    },
    {
        title: 'Clean Code',
        author: 'Robert C. Martin',
        category: 'Programim',
        pages: 464,
        description: 'Parime praktike per te shkruar kod te lexueshem dhe te mirembajtshem.',
        isbn: '978-0132350884',
        publisher: 'Prentice Hall',
        publishedYear: 2008,
        language: 'Anglisht',
        edition: 'First Edition',
        shelfLocation: 'P-01',
        availability: 'available',
        copies: 5,
        coverUrl: cover('clean-code'),
        longDescription: 'Ky liber fokusohet te zakonet e perditshme te zhvillimit software: emertime te qarta, funksione te vogla, struktura te pastra dhe testim. Eshte i dobishem per programues qe duan te rrisin cilesine e kodit.',
    },
    {
        title: 'JavaScript: The Good Parts',
        author: 'Douglas Crockford',
        category: 'Programim',
        pages: 176,
        description: 'Nje liber kompakt mbi pjeset me te forta te JavaScript.',
        isbn: '978-0596517748',
        publisher: 'OReilly Media',
        publishedYear: 2008,
        language: 'Anglisht',
        edition: 'First Edition',
        shelfLocation: 'P-02',
        availability: 'available',
        copies: 4,
        coverUrl: cover('javascript-good-parts'),
        longDescription: 'Libri perqendrohet ne sintaksen, objektet, funksionet dhe modelet me te dobishme te JavaScript. Ai ndihmon lexuesin te kuptoje cfare duhet perdorur me kujdes dhe cfare duhet shmangur.',
    },
    {
        title: 'Design Patterns',
        author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
        category: 'Programim',
        pages: 395,
        description: 'Modele klasike per zgjidhje te perseritshme ne projektimin e software.',
        isbn: '978-0201633610',
        publisher: 'Addison-Wesley',
        publishedYear: 1994,
        language: 'Anglisht',
        edition: 'First Edition',
        shelfLocation: 'P-03',
        availability: 'reserved',
        copies: 2,
        coverUrl: cover('design-patterns'),
        longDescription: 'Ky liber prezanton modele projektimi qe ndihmojne ne organizimin e kodit objekt-orientuar. Ai eshte reference per arkitekture software, komunikim teknik dhe zgjidhje qe riperdoren ne projekte te ndryshme.',
    },
    {
        title: 'Eloquent JavaScript',
        author: 'Marijn Haverbeke',
        category: 'Programim',
        pages: 472,
        description: 'Hyrje e thelle ne JavaScript, programim funksional dhe aplikacione web.',
        isbn: '978-1593279509',
        publisher: 'No Starch Press',
        publishedYear: 2018,
        language: 'Anglisht',
        edition: 'Third Edition',
        shelfLocation: 'P-04',
        availability: 'available',
        copies: 6,
        coverUrl: cover('eloquent-javascript'),
        longDescription: 'Libri kombinon teori, ushtrime dhe projekte praktike. Ai mbulon strukturat e te dhenave, funksionet, DOM-in, Node.js dhe menyren si ndertohen programe te qarta ne JavaScript.',
    },
    {
        title: 'Sapiens',
        author: 'Yuval Noah Harari',
        category: 'Histori',
        pages: 464,
        description: 'Nje veshtrim mbi historine e Homo sapiens dhe zhvillimin e shoqerise.',
        isbn: '978-0062316097',
        publisher: 'Harper',
        publishedYear: 2015,
        language: 'Anglisht',
        edition: 'Paperback',
        shelfLocation: 'H-01',
        availability: 'available',
        copies: 3,
        coverUrl: cover('sapiens'),
        longDescription: 'Harari analizon revolucionet kryesore qe kane formuar njerezimin: ate kognitiv, bujqesor dhe shkencor. Libri eshte i shkruar per lexues te gjere dhe nxit diskutim mbi kulturen, ekonomine dhe pushtetin.',
    },
    {
        title: 'Guns, Germs, and Steel',
        author: 'Jared Diamond',
        category: 'Histori',
        pages: 496,
        description: 'Analize mbi faktoret gjeografike dhe biologjike qe ndikuan ne zhvillimin e shoqerive.',
        isbn: '978-0393317558',
        publisher: 'W. W. Norton',
        publishedYear: 1997,
        language: 'Anglisht',
        edition: 'Paperback',
        shelfLocation: 'H-02',
        availability: 'borrowed',
        copies: 2,
        coverUrl: cover('guns-germs-steel'),
        longDescription: 'Libri kerkon te shpjegoje pse disa shoqeri zhvilluan teknologji, shtete dhe ekonomi me shpejt se te tjerat. Ai perdor histori, antropologji dhe gjeografi per te ndertuar argumentin.',
    },
    {
        title: 'A Short History of Nearly Everything',
        author: 'Bill Bryson',
        category: 'Histori',
        pages: 544,
        description: 'Udhetim i lexueshem ne historine e shkences dhe zbulimeve kryesore.',
        isbn: '978-0767908184',
        publisher: 'Broadway Books',
        publishedYear: 2003,
        language: 'Anglisht',
        edition: 'Paperback',
        shelfLocation: 'H-03',
        availability: 'available',
        copies: 4,
        coverUrl: cover('short-history-everything'),
        longDescription: 'Bryson shpjegon ide te medha shkencore me nje ton te qarte dhe te afrueshem. Libri kalon nga kozmosi te toka, nga kimia te biologjia dhe tregon historine e njerezve qe i zbuluan keto fusha.',
    },
    {
        title: 'The Silk Roads',
        author: 'Peter Frankopan',
        category: 'Histori',
        pages: 656,
        description: 'Histori globale e tregtise, pushtetit dhe kulturave pergjate rrugeve te medha.',
        isbn: '978-0143127741',
        publisher: 'Penguin Books',
        publishedYear: 2015,
        language: 'Anglisht',
        edition: 'Paperback',
        shelfLocation: 'H-04',
        availability: 'reserved',
        copies: 2,
        coverUrl: cover('silk-roads'),
        longDescription: 'Frankopan zhvendos qendren e historise globale drejt Azise dhe rrugeve tregtare qe lidhen kontinente. Libri tregon si mallrat, besimet dhe konfliktet kane levizur permes ketyre korridoreve.',
    },
    {
        title: 'Atomic Habits',
        author: 'James Clear',
        category: 'Zhvillim personal',
        pages: 320,
        description: 'Strategji te thjeshta per ndertimin e zakoneve te mira.',
        isbn: '978-0735211292',
        publisher: 'Avery',
        publishedYear: 2018,
        language: 'Anglisht',
        edition: 'First Edition',
        shelfLocation: 'Z-01',
        availability: 'available',
        copies: 6,
        coverUrl: cover('atomic-habits'),
        longDescription: 'Libri shpjegon si zakonet e vogla, te perseritura rregullisht, krijojne rezultate te medha. Fokusohet te sistemi, ambienti dhe identiteti si mekanizma per te ndryshuar sjelljen.',
    },
    {
        title: 'Deep Work',
        author: 'Cal Newport',
        category: 'Zhvillim personal',
        pages: 304,
        description: 'Udhezues per fokus, pune te thelle dhe shmangie te shperqendrimeve.',
        isbn: '978-1455586691',
        publisher: 'Grand Central Publishing',
        publishedYear: 2016,
        language: 'Anglisht',
        edition: 'First Edition',
        shelfLocation: 'Z-02',
        availability: 'available',
        copies: 4,
        coverUrl: cover('deep-work'),
        longDescription: 'Newport argumenton se aftesia per t’u fokusuar thelle eshte avantazh i madh profesional. Libri ofron metoda per planifikim, rutina pune dhe kontroll te teknologjise ne jeten e perditshme.',
    },
    {
        title: 'The 7 Habits of Highly Effective People',
        author: 'Stephen R. Covey',
        category: 'Zhvillim personal',
        pages: 432,
        description: 'Parime per lidership personal, prioritete dhe komunikim efektiv.',
        isbn: '978-1982137274',
        publisher: 'Simon & Schuster',
        publishedYear: 1989,
        language: 'Anglisht',
        edition: 'Anniversary Edition',
        shelfLocation: 'Z-03',
        availability: 'borrowed',
        copies: 3,
        coverUrl: cover('seven-habits'),
        longDescription: 'Covey paraqet nje kornize te bazuar ne parime per permiresim personal dhe profesional. Libri trajton proaktivitetin, prioritetet, bashkepunimin dhe zhvillimin e vazhdueshem.',
    },
    {
        title: 'Mindset',
        author: 'Carol S. Dweck',
        category: 'Zhvillim personal',
        pages: 320,
        description: 'Studim mbi mentalitetin e rritjes dhe ndikimin e tij ne sukses.',
        isbn: '978-0345472328',
        publisher: 'Ballantine Books',
        publishedYear: 2006,
        language: 'Anglisht',
        edition: 'Updated Edition',
        shelfLocation: 'Z-04',
        availability: 'available',
        copies: 5,
        coverUrl: cover('mindset'),
        longDescription: 'Dweck shpjegon dallimin midis mentalitetit fiks dhe atij te rritjes. Libri tregon si qasja ndaj gabimeve, sfidave dhe mesimit ndikon ne performance dhe zhvillim afatgjate.',
    },
    {
        title: 'The Design of Everyday Things',
        author: 'Don Norman',
        category: 'Dizajn dhe Teknologji',
        pages: 368,
        description: 'Udhezues klasik per dizajnin e qarte, te perdorshem dhe njerezor.',
        isbn: '978-0465050659',
        publisher: 'Basic Books',
        publishedYear: 2013,
        language: 'Anglisht',
        edition: 'Revised and Expanded',
        shelfLocation: 'D-01',
        availability: 'available',
        copies: 3,
        coverUrl: cover('design-everyday-things'),
        longDescription: 'Don Norman shpjegon pse objektet dhe sistemet shpesh jane te veshtira per t’u perdorur dhe si dizajni mund te permiresoje vendimmarrjen, orientimin dhe eksperiencen e perdoruesit.',
    },
    {
        title: 'Dont Make Me Think',
        author: 'Steve Krug',
        category: 'Dizajn dhe Teknologji',
        pages: 216,
        description: 'Manual praktik per usability dhe dizajn web te thjeshte.',
        isbn: '978-0321965516',
        publisher: 'New Riders',
        publishedYear: 2014,
        language: 'Anglisht',
        edition: 'Revisited',
        shelfLocation: 'D-02',
        availability: 'available',
        copies: 4,
        coverUrl: cover('dont-make-me-think'),
        longDescription: 'Krug fokusohet te thjeshtesia, orientimi vizual dhe testimi me perdorues. Libri eshte i shpejte per t’u lexuar dhe shume praktik per ndertimin e faqeve e produkteve digjitale.',
    },
    {
        title: 'Inspired',
        author: 'Marty Cagan',
        category: 'Dizajn dhe Teknologji',
        pages: 368,
        description: 'Si ndertohen produkte teknologjike qe zgjidhin probleme reale.',
        isbn: '978-1119387503',
        publisher: 'Wiley',
        publishedYear: 2017,
        language: 'Anglisht',
        edition: 'Second Edition',
        shelfLocation: 'D-03',
        availability: 'reserved',
        copies: 2,
        coverUrl: cover('inspired-cagan'),
        longDescription: 'Cagan shpjegon rolet, proceset dhe vendimmarrjen ne ekipe produkti. Libri trajton discovery, validim, strategji dhe bashkepunim midis product managers, designers dhe engineers.',
    },
    {
        title: 'Sprint',
        author: 'Jake Knapp, John Zeratsky, Braden Kowitz',
        category: 'Dizajn dhe Teknologji',
        pages: 288,
        description: 'Metode pese-ditore per te testuar ide produkti me shpejtesi.',
        isbn: '978-1501121746',
        publisher: 'Simon & Schuster',
        publishedYear: 2016,
        language: 'Anglisht',
        edition: 'First Edition',
        shelfLocation: 'D-04',
        availability: 'available',
        copies: 3,
        coverUrl: cover('sprint-book'),
        longDescription: 'Libri pershkruan nje proces intensiv per te kaluar nga problem te prototip dhe testim me perdorues. Eshte i dobishem per ekipe qe duan te ulin pasigurine para se te investojne shume kohe ne zhvillim.',
    },
];

const seedBooks = async () => {
    await connectDB();
    await Book.deleteMany({});
    await Book.insertMany(books);
    console.log(`Seeded ${books.length} books`);
    process.exit(0);
};

seedBooks().catch((error) => {
    console.error(error);
    process.exit(1);
});
